version: "3.8"

services:
  db:
    image: postgres:15-alpine
    container_name: docushield_postgres
    restart: always
    environment:
      POSTGRES_DB: docushield
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: docushield_redis
    restart: always
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    container_name: docushield_backend
    restart: always
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgrespassword@db:5432/docushield
      - UPLOAD_DIR=/app/media/uploads
      - ELA_DIR=/app/media/ela
    volumes:
      - backend_media:/app/media

  frontend:
    build: ./frontend
    container_name: docushield_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000

volumes:
  postgres_data:
  backend_media:
