from fastapi import APIRouter, UploadFile, File, HTTPException, status
from pydantic import BaseModel, Field
from app.services import ml_pipeline
import logging

logger = logging.getLogger("docushield.routers.ml")

router = APIRouter(prefix="/ml", tags=["ml"])


# Request & Response Schemas
class RiskScoreRequest(BaseModel):
    ml_score: float = Field(..., description="The fraud score generated by the ML pipeline (0-100).")
    forensic_score: float = Field(..., description="The risk score generated by the forensic analysis engine (0-100).")


class RiskScoreResponse(BaseModel):
    final_score: float = Field(..., description="The combined weighted risk score.")


class PredictResponse(BaseModel):
    prediction: str = Field(..., description="The classification prediction: 'Genuine' or 'Tampered'.")
    confidence: float = Field(..., description="Model classification confidence percentage.")


@router.post(
    "/predict", 
    response_model=PredictResponse,
    status_code=status.HTTP_200_OK,
    summary="Predict document authenticity",
    description="Analyzes an uploaded document image (PNG/JPG/JPEG) and predicts if it is Genuine or Tampered."
)
async def predict(file: UploadFile = File(..., description="Document image file to analyze")):
    # Validate file extension
    ext = file.filename.split(".")[-1].lower() if file.filename else ""
    if ext not in ["jpg", "jpeg", "png"]:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"Unsupported file format: {ext}. Only JPG, JPEG, and PNG are supported."
        )

    try:
        # Read image contents into memory bytes
        image_bytes = await file.read()
        if not image_bytes:
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail="The uploaded file is empty."
            )
            
        result = ml_pipeline.predict_document(image_bytes)
        return PredictResponse(
            prediction=result["prediction"],
            confidence=result["confidence"]
        )
    except Exception as e:
        logger.error(f"Error handling /predict request: {e}")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Prediction failed: {str(e)}"
        )


@router.post(
    "/risk-score", 
    response_model=RiskScoreResponse,
    status_code=status.HTTP_200_OK,
    summary="Combine ML and Forensic risk scores",
    description="Computes a weighted final risk score combining the ML pipeline outcome and the forensics assessment."
)
def risk_score(payload: RiskScoreRequest):
    try:
        final_score = ml_pipeline.combine_risk_score(
            ml_score=payload.ml_score,
            forensic_score=payload.forensic_score
        )
        return RiskScoreResponse(final_score=final_score)
    except Exception as e:
        logger.error(f"Error combining risk scores: {e}")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to calculate risk score: {str(e)}"
        )
