import logging
from typing import Union, Dict, Any
from app.services.inference import InferenceService

logger = logging.getLogger("docushield.ml.pipeline")

# Module level singleton pattern for inference service
_inference_service = None


def load_model() -> InferenceService:
    """
    Loads and prepares the underlying ResNet50 classifier model.
    Uses a singleton instance to prevent multiple loads of the weights.
    """
    global _inference_service
    if _inference_service is None:
        logger.info("Initializing InferenceService inside ML pipeline...")
        _inference_service = InferenceService()
    return _inference_service


def predict_document(image_input: Union[str, bytes]) -> Dict[str, Any]:
    """
    Runs the document image through the neural network to output
    whether the document is Genuine or Tampered, along with confidence.
    """
    service = load_model()
    return service.predict(image_input)


def calculate_confidence(prob: float) -> float:
    """
    Normalizes a binary raw probability value [0.0 - 1.0] into a class prediction
    confidence percentage [50.0 - 100.0].
    """
    if not (0.0 <= prob <= 1.0):
        logger.warning(f"Probability {prob} out of bounds [0.0, 1.0]. Clipping values.")
        prob = max(0.0, min(1.0, prob))
        
    if prob >= 0.5:
        confidence = prob * 100.0
    else:
        confidence = (1.0 - prob) * 100.0
        
    return round(confidence, 1)


def combine_risk_score(ml_score: float, forensic_score: float) -> float:
    """
    Combines the machine learning fraud score and forensic risk score.
    Formula:
      final_score = 0.6 * ml_score + 0.4 * forensic_score
      
    This function consumes forensic scores generated by other services
    and does not implement forensic logic.
    """
    final_score = (0.6 * ml_score) + (0.4 * forensic_score)
    return round(final_score, 2)
